name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'
      
      - name: Build Front-end
        run: |
          cd front-end
          npm install
          npm run build
        env:
          CI: false
      
      - name: Copy Front-end Build to META-INF/resources
        run: |
          mkdir -p back-end/src/main/resources/META-INF/resources
          cp -R front-end/build/* back-end/src/main/resources/META-INF/resources/
      
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
        working-directory: back-end
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: back-end

      - name: Build Docker Image
        run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/socket_car_game-jvm .
        working-directory: back-end

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push quarkus/socket_car_game-jvm